image: rocker/r-base  
test:  
   script:
    - R -e 'install.packages(c("devtools", "testthat"))'
    - R -e 'devtools::install_github("slin30/wzMisc")'
    - R -e 'install.packages("purrr")'
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual
    - R -e 'devtools::test()'